services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    networks:
      - dvwa_net

  dvwa:
    image: vulnerables/web-dvwa
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - dvwa_net
  nginx:
    image: nginx:alpine
    depends_on:
      - dvwa
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - dvwa_net


networks:
  dvwa_net:
    name: dvwa_net
    driver: bridge
